server:
  port: 8090

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    generate-ddl: true
    defer-datasource-initialization: true
  message:
    basename: messages

management:
  endpoints:
    web:
      exposure:
        include: "*"

security:
  user:
    name: jkan
    password: passw0rd